apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-backend
  namespace: decubitus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tancoding/decubitus_backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE
              value: "decubitus"
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_REFRESH_SECRET
            - name: PRIVATE_KEY_PATH
              value: "/secrets/private.pem"
            - name: SMS_API_KEY
              value: "acf971a78aa723fcf98d2f60028b3d8d"
            - name: SMS_SECRET_KEY
              value: "CxSLpcI5STir0DVj"
            - name: SMS_PROJECT_KEY
              value: "397eb9c8ed"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: private-key-volume
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: private-key-volume
          secret:
            secretName: private-key-secret
